name: ITS vacancy check (simple)

concurrency:
  group: its-vacancy-check
  cancel-in-progress: true

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分ごと
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Tokyo
      LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system tzdata (for zoneinfo)
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "playwright==1.*" "requests==2.*"
          python -m playwright install --with-deps chromium

      - name: Restore auth_state.json
        shell: bash
        run: |
          set -euo pipefail
          printf '%s' "${{ secrets.AUTH_STATE_B64 }}" | base64 -d > auth_state.json
          ls -l auth_state.json
          # 最低限の健全性チェック
          [ -s auth_state.json ] || { echo "auth_state.json empty"; exit 1; }
          head -c1 auth_state.json | grep -q '{' || { echo "auth_state.json not JSON"; exit 1; }

      - name: Run checker (headless)
        timeout-minutes: 12
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -x
          python -u check_its.py

      - name: Commit last_state.json if changed
        if: always()
        run: |
          if [ -f last_state.json ]; then
            if [ -n "$(git status --porcelain last_state.json)" ]; then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add last_state.json
              git commit -m "Update last_state.json [skip ci]"
              git push
            fi
          fi
      - name: Upload debug artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            dumps/*
            hits/*
          if-no-files-found: ignore
