name: ITS vacancy check (simple)

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分ごと
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    env:
      TZ: Asia/Tokyo
      LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "playwright==1.*" "requests==2.*"
          python -m playwright install --with-deps chromium

      - name: Restore auth_state.json
        run: echo "${{ secrets.AUTH_STATE_B64 }}" | base64 -d > auth_state.json

      - name: Run checker (headless)
        env:
          PYTHONUNBUFFERED: "1"
        run: python -u check_its.py

      - name: Commit last_state.json if changed
        if: always()
        run: |
          if [ -f last_state.json ]; then
            if [ -n "$(git status --porcelain last_state.json)" ]; then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add last_state.json
              git commit -m "Update last_state.json [skip ci]"
              git push
            fi
          fi
